# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'OrangePages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrangePages
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  
  
end
